//! No-panic baseline + checker (PR #151 of the v0.5.0 ladder).
//!
//! Two commands:
//!
//! - `cargo xtask no-panic baseline [--reset]` — show diff between source
//!   and the on-disk baseline (`policy/no-panic-baseline.toml`); with
//!   `--reset`, regenerate the baseline from a fresh source scan
//!   (single-purpose dedicated PRs only).
//! - `cargo xtask check-no-panic-family` — CI gate that fails when source
//!   contains panic-family findings exceeding the baseline counts.
//!
//! Mode is `no-new-debt`: existing baselined findings are allowed; new
//! occurrences fail the check. See [`docs/NO_PANIC_POLICY.md`](../../docs/NO_PANIC_POLICY.md).
//!
//! Source scanning is regex-based (single-line patterns only) and skips
//! test scopes by path: `tests/**`, `fuzz/**`, `crates/shiplog-testkit/**`.
//! Lines starting with `//` (line comments) are also skipped to avoid
//! false-positives in doc examples.

use anyhow::{Context, Result, bail};
use regex::Regex;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;
use std::process::Command;
use std::sync::OnceLock;

use crate::policy;
use crate::tasks::file_policy::Mode;

// ────────────────────────────────────────────────────────────────────────
// Identity + Baseline
// ────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone, Eq, PartialEq, Hash, Ord, PartialOrd)]
struct Identity {
    path: String,
    family: String,
    selector_kind: String,
    selector_callee: String,
    snippet: String,
}

#[derive(Debug, Clone, Deserialize, Serialize)]
struct BaselineEntry {
    path: String,
    family: String,
    selector_kind: String,
    selector_callee: String,
    snippet: String,
    count: usize,
}

impl BaselineEntry {
    fn identity(&self) -> Identity {
        Identity {
            path: self.path.clone(),
            family: self.family.clone(),
            selector_kind: self.selector_kind.clone(),
            selector_callee: self.selector_callee.clone(),
            snippet: self.snippet.clone(),
        }
    }
}

#[derive(Debug, Deserialize, Serialize)]
struct BaselineFile {
    schema_version: u32,
    policy: String,
    owner: String,
    status: String,
    #[serde(default)]
    policy_config: Option<PolicyConfig>,
    #[serde(default, rename = "entry")]
    entries: Vec<BaselineEntry>,
}

#[derive(Debug, Deserialize, Serialize)]
struct PolicyConfig {
    mode: String,
}

fn baseline_path(workspace_root: &Path) -> std::path::PathBuf {
    policy::policy_dir(workspace_root).join("no-panic-baseline.toml")
}

fn read_baseline(path: &Path) -> Result<BaselineFile> {
    let text =
        fs::read_to_string(path).with_context(|| format!("read baseline {}", path.display()))?;
    toml::from_str(&text).with_context(|| format!("parse baseline {}", path.display()))
}

fn read_baseline_counts(path: &Path) -> BTreeMap<Identity, usize> {
    match read_baseline(path) {
        Ok(file) => file
            .entries
            .into_iter()
            .map(|e| (e.identity(), e.count))
            .collect(),
        Err(_) => BTreeMap::new(),
    }
}

fn write_baseline(path: &Path, counts: &BTreeMap<Identity, usize>) -> Result<()> {
    let mut entries: Vec<BaselineEntry> = counts
        .iter()
        .map(|(id, count)| BaselineEntry {
            path: id.path.clone(),
            family: id.family.clone(),
            selector_kind: id.selector_kind.clone(),
            selector_callee: id.selector_callee.clone(),
            snippet: id.snippet.clone(),
            count: *count,
        })
        .collect();
    entries.sort_by(|a, b| {
        a.path
            .cmp(&b.path)
            .then(a.family.cmp(&b.family))
            .then(a.selector_callee.cmp(&b.selector_callee))
            .then(a.snippet.cmp(&b.snippet))
    });
    let file = BaselineFile {
        schema_version: 1,
        policy: "no-panic-baseline".to_string(),
        owner: "EffortlessMetrics".to_string(),
        status: "advisory".to_string(),
        policy_config: Some(PolicyConfig {
            mode: "no-new-debt".to_string(),
        }),
        entries,
    };
    let header = "# Generated by `cargo xtask no-panic baseline --reset`. Do not hand-edit.\n# See docs/NO_PANIC_POLICY.md.\n\n";
    let body = toml::to_string_pretty(&file).context("serialize baseline")?;
    fs::write(path, header.to_string() + &body)
        .with_context(|| format!("write {}", path.display()))?;
    Ok(())
}

// ────────────────────────────────────────────────────────────────────────
// Source scanning
// ────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
struct PatternSpec {
    family: &'static str,
    selector_kind: &'static str,
    selector_callee: &'static str,
}

fn unwrap_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r"\.unwrap\s*\(\s*\)").expect("static regex"))
}

fn expect_re() -> &'static Regex {
    static RE: OnceLock<Regex> = OnceLock::new();
    RE.get_or_init(|| Regex::new(r#"\.expect\s*\(\s*"[^"]*"\s*\)"#).expect("static regex"))
}

fn macro_re(name: &'static str) -> Regex {
    Regex::new(&format!(r"\b{name}\s*!\s*\(")).expect("static regex")
}

fn scan_workspace(workspace_root: &Path) -> Result<BTreeMap<Identity, usize>> {
    let files = git_ls_rs_files(workspace_root)?;
    let mut counts: BTreeMap<Identity, usize> = BTreeMap::new();
    for file in &files {
        if is_test_scope(file) {
            continue;
        }
        let path = workspace_root.join(file);
        let Ok(text) = fs::read_to_string(&path) else {
            continue;
        };
        for line in text.lines() {
            let trimmed_for_skip = line.trim_start();
            if trimmed_for_skip.starts_with("//") {
                continue;
            }
            scan_line(file, line, &mut counts);
        }
    }
    Ok(counts)
}

fn scan_line(file: &str, line: &str, counts: &mut BTreeMap<Identity, usize>) {
    let snippet = line.trim().to_string();
    if unwrap_re().is_match(line) {
        bump(
            counts,
            file,
            PatternSpec {
                family: "unwrap",
                selector_kind: "method-call",
                selector_callee: "Option/Result::unwrap",
            },
            &snippet,
        );
    }
    if expect_re().is_match(line) {
        bump(
            counts,
            file,
            PatternSpec {
                family: "expect",
                selector_kind: "method-call",
                selector_callee: "Option/Result::expect",
            },
            &snippet,
        );
    }
    for (name, family) in [
        ("panic", "panic"),
        ("unreachable", "unreachable"),
        ("todo", "todo"),
        ("unimplemented", "unimplemented"),
    ] {
        if macro_re(name).is_match(line) {
            bump(
                counts,
                file,
                PatternSpec {
                    family,
                    selector_kind: "macro-call",
                    selector_callee: name,
                },
                &snippet,
            );
        }
    }
}

fn bump(counts: &mut BTreeMap<Identity, usize>, file: &str, spec: PatternSpec, snippet: &str) {
    let id = Identity {
        path: file.replace('\\', "/"),
        family: spec.family.to_string(),
        selector_kind: spec.selector_kind.to_string(),
        selector_callee: spec.selector_callee.to_string(),
        snippet: snippet.to_string(),
    };
    *counts.entry(id).or_insert(0) += 1;
}

fn is_test_scope(path: &str) -> bool {
    let p = path.replace('\\', "/");
    p.starts_with("tests/")
        || p.contains("/tests/")
        || p.starts_with("fuzz/")
        || p.starts_with("crates/shiplog-testkit/")
        || p.starts_with("xtask/")
        || p == "build.rs"
        || p.ends_with("/build.rs")
}

fn git_ls_rs_files(workspace_root: &Path) -> Result<Vec<String>> {
    let output = Command::new("git")
        .args(["ls-files", "*.rs"])
        .current_dir(workspace_root)
        .output()
        .context("invoke git ls-files *.rs")?;
    if !output.status.success() {
        bail!(
            "git ls-files *.rs failed: {}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
    Ok(String::from_utf8(output.stdout)
        .context("git output not valid UTF-8")?
        .lines()
        .filter(|l| !l.is_empty())
        .map(String::from)
        .collect())
}

// ────────────────────────────────────────────────────────────────────────
// Public entry points
// ────────────────────────────────────────────────────────────────────────

pub fn baseline(workspace_root: &Path, reset: bool) -> Result<()> {
    let baseline_path = baseline_path(workspace_root);
    let actual = scan_workspace(workspace_root)?;
    if reset {
        write_baseline(&baseline_path, &actual)?;
        println!(
            "Wrote no-panic baseline ({} entries, {} occurrences) to {}",
            actual.len(),
            actual.values().sum::<usize>(),
            baseline_path.display()
        );
        return Ok(());
    }
    let current = read_baseline_counts(&baseline_path);
    let (added, removed, changed) = diff(&current, &actual);
    println!(
        "no-panic baseline diff: +{} new identities, -{} stale identities, {} count changes",
        added.len(),
        removed.len(),
        changed.len()
    );
    if !added.is_empty() {
        println!();
        println!("New identities (would fail check-no-panic-family):");
        for (id, count) in &added {
            println!(
                "  {} :: {} :: {} :: count={}",
                id.path, id.family, id.snippet, count
            );
        }
    }
    if !removed.is_empty() {
        println!();
        println!("Stale baseline identities (run --reset to drop):");
        for (id, _) in &removed {
            println!("  {} :: {} :: {}", id.path, id.family, id.snippet);
        }
    }
    if !changed.is_empty() {
        println!();
        println!("Count changes (baseline → actual):");
        for (id, baseline_count, actual_count) in &changed {
            println!(
                "  {} :: {} :: {} :: {} → {}",
                id.path, id.family, id.snippet, baseline_count, actual_count
            );
        }
    }
    Ok(())
}

pub fn check_no_panic_family(workspace_root: &Path, mode: Mode) -> Result<()> {
    let baseline_path = baseline_path(workspace_root);
    let baseline = read_baseline_counts(&baseline_path);
    let actual = scan_workspace(workspace_root)?;

    let mut findings = Vec::new();

    // New identities or higher counts (no-new-debt).
    for (id, count) in &actual {
        let baseline_count = baseline.get(id).copied().unwrap_or(0);
        if *count > baseline_count {
            findings.push(format!(
                "[new-panic-debt] {} :: {} :: {} :: count {} > baseline {}",
                id.path, id.family, id.snippet, count, baseline_count
            ));
        }
    }
    // Stale baseline entries (paid-down debt — informational only, NOT a
    // hard finding; it just means the baseline can shrink).
    let mut stale = Vec::new();
    for id in baseline.keys() {
        if !actual.contains_key(id) {
            stale.push(format!("  {} :: {} :: {}", id.path, id.family, id.snippet));
        }
    }

    if findings.is_empty() {
        println!("check-no-panic-family: no new panic-family debt.");
        if !stale.is_empty() {
            println!(
                "{} stale baseline entries (debt has been paid down — run `cargo xtask no-panic baseline --reset` in a dedicated PR to shrink the baseline):",
                stale.len()
            );
            for s in &stale {
                println!("{s}");
            }
        }
        return Ok(());
    }

    println!("check-no-panic-family: {} finding(s).", findings.len());
    for f in &findings {
        eprintln!("  {f}");
    }
    if !stale.is_empty() {
        println!();
        println!(
            "(also: {} stale baseline entries; not failing on these)",
            stale.len()
        );
    }
    match mode {
        Mode::Advisory => {
            println!("(advisory mode: not failing)");
            Ok(())
        }
        Mode::BlockingAllowlist => {
            bail!(
                "check-no-panic-family: {} finding(s) (blocking-allowlist mode)",
                findings.len()
            )
        }
    }
}

// ────────────────────────────────────────────────────────────────────────
// Diff helpers
// ────────────────────────────────────────────────────────────────────────

type AddedRemoved = Vec<(Identity, usize)>;
type CountChanges = Vec<(Identity, usize, usize)>;

fn diff(
    baseline: &BTreeMap<Identity, usize>,
    actual: &BTreeMap<Identity, usize>,
) -> (AddedRemoved, AddedRemoved, CountChanges) {
    let mut added = Vec::new();
    let mut changed = Vec::new();
    for (id, actual_count) in actual {
        match baseline.get(id) {
            None => added.push((id.clone(), *actual_count)),
            Some(base) => {
                if base != actual_count {
                    changed.push((id.clone(), *base, *actual_count));
                }
            }
        }
    }
    let mut removed = Vec::new();
    for (id, count) in baseline {
        if !actual.contains_key(id) {
            removed.push((id.clone(), *count));
        }
    }
    (added, removed, changed)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn fixture(files: &[(&str, &str)]) -> tempfile::TempDir {
        let dir = tempdir().unwrap();
        for (name, content) in files {
            let path = dir.path().join(name);
            if let Some(parent) = path.parent() {
                fs::create_dir_all(parent).unwrap();
            }
            fs::write(path, content).unwrap();
        }
        let _ = Command::new("git")
            .args(["init", "-q"])
            .current_dir(dir.path())
            .output();
        let _ = Command::new("git")
            .args(["add", "-A"])
            .current_dir(dir.path())
            .output();
        dir
    }

    #[test]
    fn unwrap_pattern_matches_method_call() {
        assert!(unwrap_re().is_match("    let x = foo.unwrap();"));
        assert!(unwrap_re().is_match("foo .unwrap()"));
        assert!(!unwrap_re().is_match("// unwrap()"));
        // `unwrap` not as method call — should not match
        assert!(!unwrap_re().is_match("fn unwrap_inner() {}"));
    }

    #[test]
    fn expect_pattern_matches_method_call_with_message() {
        assert!(expect_re().is_match(r#"foo.expect("bar")"#));
        assert!(expect_re().is_match(r#"foo .expect("multi word reason")"#));
        // No string arg — does not match
        assert!(!expect_re().is_match("foo.expect(x)"));
    }

    #[test]
    fn macro_pattern_matches_panic_family_macros() {
        assert!(macro_re("panic").is_match("panic!(\"x\")"));
        assert!(macro_re("unreachable").is_match("    unreachable!();"));
        assert!(macro_re("todo").is_match("todo!()"));
        assert!(macro_re("unimplemented").is_match("unimplemented!()"));
        // Identifier prefix (e.g. fn name) shouldn't match
        assert!(!macro_re("panic").is_match("fn panicky() {}"));
    }

    #[test]
    fn scan_skips_test_scope_paths() {
        assert!(is_test_scope("tests/foo.rs"));
        assert!(is_test_scope("crates/foo/tests/bar.rs"));
        assert!(is_test_scope("fuzz/fuzz_targets/foo.rs"));
        assert!(is_test_scope("crates/shiplog-testkit/src/lib.rs"));
        assert!(is_test_scope("xtask/src/main.rs"));
        assert!(is_test_scope("xtask/src/tasks/no_panic.rs"));
        assert!(is_test_scope("build.rs"));
        assert!(is_test_scope("crates/foo/build.rs"));
        assert!(!is_test_scope("crates/shiplog-engine/src/lib.rs"));
        assert!(!is_test_scope("apps/shiplog/src/main.rs"));
    }

    #[test]
    fn workspace_scan_skips_line_comments() {
        let dir = fixture(&[(
            "crates/foo/src/lib.rs",
            "// example: foo.unwrap() — this is in a comment\nfn x() {}\n",
        )]);
        let actual = scan_workspace(dir.path()).expect("scan");
        // The comment line shouldn't contribute, so no findings.
        assert_eq!(actual.len(), 0);
    }

    #[test]
    fn workspace_scan_round_trips_through_baseline() {
        let dir = fixture(&[
            (
                "crates/foo/src/lib.rs",
                "fn foo() {\n    let x = bar.unwrap();\n    panic!(\"oops\");\n}\n",
            ),
            ("policy/.gitkeep", ""),
        ]);
        let actual = scan_workspace(dir.path()).expect("scan");
        // Two identities: one unwrap, one panic.
        assert_eq!(actual.len(), 2);
        assert!(actual.values().all(|&c| c == 1));

        // Round-trip through write/read.
        let path = dir.path().join("policy/no-panic-baseline.toml");
        write_baseline(&path, &actual).expect("write");
        let read = read_baseline_counts(&path);
        assert_eq!(read, actual);
    }

    #[test]
    fn workspace_scan_skips_test_files() {
        let dir = fixture(&[
            ("crates/foo/src/lib.rs", "fn x() { y.unwrap(); }\n"),
            ("crates/foo/tests/it.rs", "fn t() { y.unwrap(); }\n"),
            (
                "crates/shiplog-testkit/src/lib.rs",
                "fn t() { y.unwrap(); }\n",
            ),
            ("fuzz/fuzz_targets/x.rs", "fn t() { y.unwrap(); }\n"),
        ]);
        let actual = scan_workspace(dir.path()).expect("scan");
        // Only the non-test source file contributes
        assert_eq!(actual.len(), 1);
        let id = actual.keys().next().unwrap();
        assert_eq!(id.path, "crates/foo/src/lib.rs");
    }

    #[test]
    fn check_passes_when_actual_matches_baseline() {
        let dir = fixture(&[
            ("crates/foo/src/lib.rs", "fn x() { y.unwrap(); }\n"),
            ("policy/.gitkeep", ""),
        ]);
        // Generate the baseline.
        baseline(dir.path(), true).expect("reset baseline");
        // Now check should pass.
        check_no_panic_family(dir.path(), Mode::BlockingAllowlist).expect("check passes");
    }

    #[test]
    fn check_fails_when_new_panic_added() {
        let dir = fixture(&[
            ("crates/foo/src/lib.rs", "fn x() { y.unwrap(); }\n"),
            ("policy/.gitkeep", ""),
        ]);
        baseline(dir.path(), true).expect("reset baseline");
        // Add a new panic site.
        fs::write(
            dir.path().join("crates/foo/src/lib.rs"),
            "fn x() { y.unwrap(); }\nfn z() { panic!(\"new\"); }\n",
        )
        .unwrap();
        let err = check_no_panic_family(dir.path(), Mode::BlockingAllowlist).expect_err("new debt");
        assert!(format!("{err:#}").contains("check-no-panic-family"));
    }

    #[test]
    fn check_passes_when_panic_removed_below_baseline() {
        let dir = fixture(&[
            (
                "crates/foo/src/lib.rs",
                "fn x() { y.unwrap(); }\nfn z() { y.unwrap(); }\n",
            ),
            ("policy/.gitkeep", ""),
        ]);
        baseline(dir.path(), true).expect("reset baseline");
        // Remove one of the unwrap occurrences (paid down debt).
        fs::write(
            dir.path().join("crates/foo/src/lib.rs"),
            "fn x() { y.unwrap(); }\nfn z() { /* paid down */ }\n",
        )
        .unwrap();
        // Should pass — paid-down debt is allowed; baseline can shrink.
        check_no_panic_family(dir.path(), Mode::BlockingAllowlist)
            .expect("paid-down debt is allowed");
    }
}
